# Generated by Django 3.2.7 on 2021-11-30 03:33

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fields_job', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_post', models.CharField(max_length=200)),
                ('time_create', models.DateTimeField(default=datetime.datetime(2021, 11, 30, 10, 33, 31, 865128))),
                ('experience_required', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('content_post', ckeditor.fields.RichTextField(max_length=2000)),
                ('type_job', models.CharField(max_length=100)),
                ('confirm', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('field_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fields_job.fieldjob')),
            ],
        ),
        migrations.CreateModel(
            name='Post_apply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status_apply', models.CharField(blank=True, max_length=20, null=True)),
                ('post_apply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.post')),
                ('user_apply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user_apply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.post_apply'),
        ),
    ]
