# Generated by Django 3.2.7 on 2021-11-01 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_post', models.CharField(max_length=200)),
                ('time_create', models.DateTimeField(default=datetime.datetime(2021, 11, 1, 13, 17, 24, 221434))),
                ('experience_required', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('content_post', models.CharField(max_length=1000)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
    ]
