# Generated by Django 3.2.7 on 2021-11-02 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type_job',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 13, 43, 44, 259086)),
        ),
    ]
