# Generated by Django 3.2.7 on 2021-11-02 06:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fields_job', '__first__'),
        ('posts', '0003_auto_20211102_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='field_job',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='fields_job.fieldjob'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 13, 58, 51, 560385)),
        ),
    ]
