# Generated by Django 3.2.7 on 2021-11-30 03:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 10, 37, 8, 563813)),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_apply',
            field=models.ForeignKey(blank=True, default='wait_accept', null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.post_apply'),
        ),
    ]
