# Generated by Django 3.2.7 on 2021-11-30 04:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20211130_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 11, 9, 32, 136705)),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_apply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.post_apply'),
        ),
        migrations.AlterField(
            model_name='post_apply',
            name='status_apply',
            field=models.CharField(blank=True, default='wait_accept', max_length=20, null=True),
        ),
    ]
