# Generated by Django 3.2.7 on 2021-11-17 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20211117_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comfirm',
            new_name='confirm',
        ),
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 22, 34, 34, 56986)),
        ),
    ]
