# Generated by Django 3.2.7 on 2021-11-18 10:13

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20211117_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_post',
            field=ckeditor.fields.RichTextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 17, 13, 25, 946826)),
        ),
    ]
