<<<<<<< HEAD
# Generated by Django 3.2.7 on 2021-11-02 07:06
=======
# Generated by Django 3.2.8 on 2021-11-01 16:55
>>>>>>> d67648326fe80dd6a33f0febebef915cba2bcc48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('posts', '0006_auto_20211102_1402'),
=======
        ('posts', '0006_alter_post_time_create'),
>>>>>>> d67648326fe80dd6a33f0febebef915cba2bcc48
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_create',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 14, 6, 40, 924581)),
=======
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 23, 55, 40, 906024)),
>>>>>>> d67648326fe80dd6a33f0febebef915cba2bcc48
        ),
    ]
