# Generated by Django 3.2.7 on 2021-11-04 09:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fields_job', '__first__'),
        ('posts', '0012_alter_post_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='field_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fields_job.fieldjob'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 16, 43, 18, 282769)),
        ),
    ]
