# Generated by Django 3.2.7 on 2021-11-05 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_skill', '0001_initial'),
        ('posts', '0013_auto_20211104_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag_skill',
            field=models.ManyToManyField(blank=True, null=True, to='tag_skill.TagSkill'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 0, 22, 7, 156715)),
        ),
    ]
