# Generated by Django 3.2.8 on 2021-11-18 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='default-profile-picture.jpg', null=True, upload_to='profile-picture')),
                ('full_name', models.CharField(blank=True, max_length=128, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.PositiveBigIntegerField(blank=True, choices=[(1, 'Name'), (2, 'Nữ')], null=True)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(blank=True, max_length=1000, null=True)),
                ('name_of_school', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_degree', models.CharField(blank=True, max_length=128, null=True)),
                ('name_of_major', models.CharField(blank=True, max_length=255, null=True)),
                ('time_admission', models.DateField(blank=True, null=True)),
                ('time_graduate', models.DateField(blank=True, null=True)),
                ('is_studying', models.BooleanField(default=False)),
                ('additional_education', models.TextField(blank=True, null=True)),
                ('name_of_previous_company', models.CharField(blank=True, max_length=128, null=True)),
                ('previous_job_title', models.CharField(blank=True, max_length=128, null=True)),
                ('time_start_previous_job', models.DateField(blank=True, null=True)),
                ('time_end_previous_job', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
