# Generated by Django 3.2.8 on 2021-11-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='desired_salary',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='desired_working_location',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name_of_interested_job',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='type_of_job',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Part-time'), (2, 'Full-time'), (3, 'Internship'), (4, 'Freelance')], null=True),
        ),
    ]
