# Generated by Django 3.2.8 on 2021-11-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name_of_previous_company',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='previous_job_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='time_end_previous_job',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='time_start_previous_job',
            field=models.DateField(blank=True, null=True),
        ),
    ]
