# Generated by Django 3.2.8 on 2021-11-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20211127_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_updated_iterested_job',
            field=models.BooleanField(default=False),
        ),
    ]
