# Generated by Django 3.2.8 on 2021-11-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_name_of_volunteering_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_updated_education',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_updated_previous_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_updated_project_participated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_updated_volunteering_activity',
            field=models.BooleanField(default=False),
        ),
    ]
