# Generated by Django 3.2.8 on 2021-11-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default-profile-picture.jpg', null=True, upload_to=''),
        ),
    ]
