# Generated by Django 3.2.8 on 2021-11-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20211118_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_joining',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='role_in_volunteering_activity',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='time_end_volunteering_activity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='time_start_volunteering_activity',
            field=models.DateField(blank=True, null=True),
        ),
    ]
