# Generated by Django 3.2.8 on 2021-11-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20211121_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='summary_company',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
