# Generated by Django 3.2.8 on 2021-11-27 18:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_is_updated_iterested_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='type_of_job',
        ),
        migrations.AddField(
            model_name='profile',
            name='list_type_of_job',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Part-time'), (2, 'Full-time'), (3, 'Internship'), (4, 'Freelance')], null=True), null=True, size=4),
        ),
    ]
