# Generated by Django 3.2.8 on 2021-11-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20211118_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_updated_summary',
            field=models.BooleanField(default=False),
        ),
    ]
