# Generated by Django 3.2.8 on 2021-11-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_recruiterprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruiterprofile',
            options={'verbose_name': 'Profile Recruiter', 'verbose_name_plural': 'Profiles Recruiter'},
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='is_updated_basic_information_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='profile_picture_company',
            field=models.ImageField(blank=True, default='default-profile-picture.jpg', null=True, upload_to='profile-picture'),
        ),
    ]
