# Generated by Django 3.2.5 on 2021-10-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='email',
            field=models.EmailField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='company_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='email',
            field=models.EmailField(max_length=256, null=True),
        ),
    ]
