# Generated by Django 3.2.8 on 2021-12-06 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_alter_post_time_create'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_notification', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Profile is created'), (2, 'Profile is updated'), (3, 'Post is applied')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_notification', to=settings.AUTH_USER_MODEL)),
                ('recruitment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_post', to='posts.post')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creater_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
