# Generated by Django 3.2.8 on 2021-12-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_recruitment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_of_notification',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Account is created'), (2, 'Profile is updated'), (3, 'Post is applied')], null=True),
        ),
    ]
